name: Hello World

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  sapa:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Cetak pesan
        run: echo "Halo! Workflow pertama berhasil jalan!"

      - name: Cetak tanggal
        run: date
