name: Hello World

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  sapa:
    runs-on: ubuntu-latest

    steps:
      - name: Cetak pesan
        run: echo "Halo! Workflow pertama berhasil jalan!"

      - name: Cetak tanggal
        run: date
