name: Pakai Secret

on:
  workflow_dispatch:

jobs:
  rahasia:
    runs-on: ubuntu-latest

    steps:
      - name: Gunakan secret
        env:
          PESAN: ${{ secrets.PESAN_RAHASIA }}
        run: |
          echo "Secret berhasil dibaca!"
          echo "Isi secret: $PESAN"
          echo "Di log Actions, secret tampil sebagai: ${{ secrets.PESAN_RAHASIA }}"

      - name: Buktikan secret tersembunyi di log
        run: |
          echo "Coba tampilkan secret langsung:"
          echo "${{ secrets.PESAN_RAHASIA }}"
